### ISSUE TITLE
Error: panic: interface conversion: interface {} is *parser.Set, not int

### ISSUE THREAD

**Issue by TCB13** [stephenlyu/goqtuic#5]
Hello,

Many thanks to this great tool, I was trying to use it again after to convert a small tool a long time and this is what I got:

```
goqtuic.exe -ui-file .\lofloccus.ui
Translating .\lofloccus.ui...
2019/04/25 11:12:26 [WARN][github.com/stephenlyu/goqtuic/parser] compiler.go:1236: Should add code for GroupBox inner widget?
2019/04/25 11:12:26 [WARN][github.com/stephenlyu/goqtuic/parser] compiler.go:1236: Should add code for GroupBox inner widget?
2019/04/25 11:12:26 [WARN][github.com/stephenlyu/goqtuic/parser] compiler.go:1236: Should add code for GroupBox2 inner widget?
panic: interface conversion: interface {} is *parser.Set, not int

goroutine 1 [running]:
github.com/stephenlyu/goqtuic/parser.(*compiler).translateLayout(0xc00005ca90, 0xc000155420, 0x16, 0xc0000e6180)
        C:/Users/TCB13/go/src/github.com/stephenlyu/goqtuic/parser/compiler.go:748 +0x162f
github.com/stephenlyu/goqtuic/parser.(*compiler).translateWidget(0xc00005ca90, 0xc000129e80, 0xe, 0xc00009d0e0)
        C:/Users/TCB13/go/src/github.com/stephenlyu/goqtuic/parser/compiler.go:1207 +0x17af
github.com/stephenlyu/goqtuic/parser.(*compiler).translateWidget(0xc00005ca90, 0xc000155220, 0x12, 0xc00009d200)
        C:/Users/TCB13/go/src/github.com/stephenlyu/goqtuic/parser/compiler.go:1212 +0xba7
github.com/stephenlyu/goqtuic/parser.(*compiler).translateWidget(0xc00005ca90, 0xc000129030, 0xa, 0xc00014c240)
        C:/Users/TCB13/go/src/github.com/stephenlyu/goqtuic/parser/compiler.go:1212 +0xba7
github.com/stephenlyu/goqtuic/parser.(*compiler).GenerateCode(0xc00005ca90, 0xc00000c4cd, 0x5, 0xc000012380, 0x32, 0xc00000a380, 0xf)
        C:/Users/TCB13/go/src/github.com/stephenlyu/goqtuic/parser/compiler.go:1378 +0x2c8
main.translateUIFile(0xc00000a0d0, 0xe, 0x70718a, 0x5, 0x0, 0x0, 0x11, 0xc00004abf0)
        C:/Users/TCB13/go/src/github.com/stephenlyu/goqtuic/main.go:27 +0x30a
main.main()
        C:/Users/TCB13/go/src/github.com/stephenlyu/goqtuic/main.go:87 +0x228
```

Just for reference, you can find my `.ui` file attached.
[lofloccus.zip](https://github.com/stephenlyu/goqtuic/files/3116406/lofloccus.zip)

Any tips? Also, what should I do about the warnings?

Thank you.

**Comment by jifanchn** [comment]
I have successfully generated your .ui file as below with some warnings. (Also on linux)

```
PS C:\Users\gamej\go\src\goqtuic> goqtuic.exe -ui-file lofloccus.ui
Translating lofloccus.ui...
2020/12/17 16:03:25 [WARN][goqtuic/parser] compiler.go:1244: Should add code for GroupBox inner widget?
2020/12/17 16:03:25 [WARN][goqtuic/parser] compiler.go:1244: Should add code for GroupBox inner widget?
2020/12/17 16:03:25 [WARN][goqtuic/parser] compiler.go:1244: Should add code for GroupBox2 inner widget?
2020/12/17 16:03:25 [WARN][goqtuic/parser] compiler.go:1244: Should add code for GroupBox2 inner widget?
2020/12/17 16:03:25 [WARN][goqtuic/parser] compiler.go:1244: Should add code for GroupBox3 inner widget?
2020/12/17 16:03:25 [WARN][goqtuic/parser] compiler.go:1244: Should add code for GroupBox3 inner widget?
```

And the result is also attached.

```
// WARNING! All changes made in this file will be lost!
package uigen

import (
	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"
	"github.com/therecipe/qt/gui"
)

type UILofloccusMainWindow struct {
	Centralwidget *widgets.QWidget
	GroupBox *widgets.QGroupBox
	StartMinimized *widgets.QCheckBox
	StartOpen *widgets.QCheckBox
	GroupBox2 *widgets.QGroupBox
	Label *widgets.QLabel
	FormLayoutWidget2 *widgets.QWidget
	 *widgets.QFormLayout
	SrvAddr *widgets.QLabel
	Label10 *widgets.QLabel
	Label11 *widgets.QLabel
	SrvUser *widgets.QLabel
	Label12 *widgets.QLabel
	SrvPasswd *widgets.QLabel
	GroupBox3 *widgets.QGroupBox
	FormLayoutWidget *widgets.QWidget
	 *widgets.QFormLayout
	SrvStatus *widgets.QLabel
	Label6 *widgets.QLabel
	Label7 *widgets.QLabel
	XbelPath *widgets.QLabel
	 *widgets.QWidget
	GridLayout *widgets.QGridLayout
	XbelLocaltion *widgets.QPushButton
	ServerControl *widgets.QPushButton
	HideTray *widgets.QPushButton
	Label5 *widgets.QLabel
	Label8 *widgets.QLabel
	Label9 *widgets.QLabel
	Statusbar *widgets.QStatusBar
}

func (this *UILofloccusMainWindow) SetupUI(MainWindow *widgets.QMainWindow) {
	MainWindow.SetObjectName("MainWindow")
	MainWindow.SetEnabled(true)
	MainWindow.SetGeometry(core.NewQRect4(0, 0, 461, 442))
	var sizePolicy *widgets.QSizePolicy
	sizePolicy = widgets.NewQSizePolicy2(widgets.QSizePolicy__Fixed, widgets.QSizePolicy__Expanding, widgets.QSizePolicy__DefaultType)
	sizePolicy.SetHorizontalStretch(0)
	sizePolicy.SetVerticalStretch(0)
	sizePolicy.SetHeightForWidth(MainWindow.SizePolicy().HasHeightForWidth())
	MainWindow.SetSizePolicy(sizePolicy)
	MainWindow.SetBaseSize(core.NewQSize2(461, 434))
	var icon *gui.QIcon
	icon = gui.NewQIcon()
	icon.AddPixmap(gui.NewQPixmap5("../Source/GitHub/LoFloccus/icon.ico", "", core.Qt__AutoColor), gui.QIcon__Normal, gui.QIcon__Off)
	MainWindow.SetWindowIcon(icon)
	MainWindow.SetLocale(core.NewQLocale3(core.QLocale__English, core.QLocale__UnitedStates))
	MainWindow.SetDocumentMode(false)
	this.Centralwidget = widgets.NewQWidget(MainWindow, core.Qt__Widget)
	this.Centralwidget.SetObjectName("Centralwidget")
	this.GroupBox = widgets.NewQGroupBox(this.Centralwidget)
	this.GroupBox.SetObjectName("GroupBox")
	this.GroupBox.SetGeometry(core.NewQRect4(10, 350, 441, 71))
	var font *gui.QFont
	font = gui.NewQFont()
	font.SetWeight(75)
	this.GroupBox.SetFont(font)
	this.StartMinimized = widgets.NewQCheckBox(this.GroupBox)
	this.StartMinimized.SetObjectName("StartMinimized")
	this.StartMinimized.SetGeometry(core.NewQRect4(10, 20, 361, 17))
	font = gui.NewQFont()
	font.SetWeight(50)
	this.StartMinimized.SetFont(font)
	this.StartOpen = widgets.NewQCheckBox(this.GroupBox)
	this.StartOpen.SetObjectName("StartOpen")
	this.StartOpen.SetGeometry(core.NewQRect4(10, 40, 361, 17))
	font = gui.NewQFont()
	font.SetWeight(50)
	this.StartOpen.SetFont(font)
	this.GroupBox2 = widgets.NewQGroupBox(this.Centralwidget)
	this.GroupBox2.SetObjectName("GroupBox2")
	this.GroupBox2.SetGeometry(core.NewQRect4(10, 220, 441, 121))
	font = gui.NewQFont()
	font.SetWeight(75)
	this.GroupBox2.SetFont(font)
	this.GroupBox2.SetFlat(false)
	this.GroupBox2.SetCheckable(false)
	this.Label = widgets.NewQLabel(this.GroupBox2, core.Qt__Widget)
	this.Label.SetObjectName("Label")
	this.Label.SetGeometry(core.NewQRect4(10, 20, 421, 31))
	font = gui.NewQFont()
	font.SetWeight(50)
	this.Label.SetFont(font)
	this.Label.SetTextFormat(core.Qt__PlainText)
	this.Label.SetAlignment(core.Qt__AlignLeading | core.Qt__AlignLeft | core.Qt__AlignTop)
	this.FormLayoutWidget2 = widgets.NewQWidget(this.GroupBox2, core.Qt__Widget)
	this.FormLayoutWidget2.SetObjectName("FormLayoutWidget2")
	this.FormLayoutWidget2.SetGeometry(core.NewQRect4(10, 48, 421, 61))
	this. = widgets.NewQFormLayout(this.FormLayoutWidget2)
	this..SetObjectName("_2")
	this..SetContentsMargins(0, 0, 0, 0)
	this..SetSpacing(0)
	this..SetFormAlignment(core.Qt__AlignLeading | core.Qt__AlignLeft | core.Qt__AlignVCenter)
	this..SetHorizontalSpacing(20)
	this..SetVerticalSpacing(5)
	this.SrvAddr = widgets.NewQLabel(this.FormLayoutWidget2, core.Qt__Widget)
	this.SrvAddr.SetObjectName("SrvAddr")
	font = gui.NewQFont()
	font.SetWeight(50)
	this.SrvAddr.SetFont(font)
	this..SetWidget(0, widgets.QFormLayout__FieldRole, this.SrvAddr)
	this.Label10 = widgets.NewQLabel(this.FormLayoutWidget2, core.Qt__Widget)
	this.Label10.SetObjectName("Label10")
	font = gui.NewQFont()
	font.SetWeight(50)
	this.Label10.SetFont(font)
	this..SetWidget(0, widgets.QFormLayout__LabelRole, this.Label10)
	this.Label11 = widgets.NewQLabel(this.FormLayoutWidget2, core.Qt__Widget)
	this.Label11.SetObjectName("Label11")
	font = gui.NewQFont()
	font.SetWeight(50)
	this.Label11.SetFont(font)
	this..SetWidget(1, widgets.QFormLayout__LabelRole, this.Label11)
	this.SrvUser = widgets.NewQLabel(this.FormLayoutWidget2, core.Qt__Widget)
	this.SrvUser.SetObjectName("SrvUser")
	font = gui.NewQFont()
	font.SetWeight(50)
	this.SrvUser.SetFont(font)
	this..SetWidget(1, widgets.QFormLayout__FieldRole, this.SrvUser)
	this.Label12 = widgets.NewQLabel(this.FormLayoutWidget2, core.Qt__Widget)
	this.Label12.SetObjectName("Label12")
	font = gui.NewQFont()
	font.SetWeight(50)
	this.Label12.SetFont(font)
	this..SetWidget(2, widgets.QFormLayout__LabelRole, this.Label12)
	this.SrvPasswd = widgets.NewQLabel(this.FormLayoutWidget2, core.Qt__Widget)
	this.SrvPasswd.SetObjectName("SrvPasswd")
	font = gui.NewQFont()
	font.SetWeight(50)
	this.SrvPasswd.SetFont(font)
	this..SetWidget(2, widgets.QFormLayout__FieldRole, this.SrvPasswd)
	this.GroupBox3 = widgets.NewQGroupBox(this.Centralwidget)
	this.GroupBox3.SetObjectName("GroupBox3")
	this.GroupBox3.SetGeometry(core.NewQRect4(10, 110, 441, 101))
	font = gui.NewQFont()
	font.SetWeight(75)
	this.GroupBox3.SetFont(font)
	this.FormLayoutWidget = widgets.NewQWidget(this.GroupBox3, core.Qt__Widget)
	this.FormLayoutWidget.SetObjectName("FormLayoutWidget")
	this.FormLayoutWidget.SetGeometry(core.NewQRect4(9, 20, 421, 34))
	this. = widgets.NewQFormLayout(this.FormLayoutWidget)
	this..SetObjectName("")
	this..SetContentsMargins(0, 0, 0, 0)
	this..SetSpacing(0)
	this..SetHorizontalSpacing(20)
	this..SetVerticalSpacing(5)
	this.SrvStatus = widgets.NewQLabel(this.FormLayoutWidget, core.Qt__Widget)
	this.SrvStatus.SetObjectName("SrvStatus")
	font = gui.NewQFont()
	font.SetWeight(75)
	this.SrvStatus.SetFont(font)
	this..SetWidget(0, widgets.QFormLayout__FieldRole, this.SrvStatus)
	this.Label6 = widgets.NewQLabel(this.FormLayoutWidget, core.Qt__Widget)
	this.Label6.SetObjectName("Label6")
	font = gui.NewQFont()
	font.SetWeight(50)
	this.Label6.SetFont(font)
	this..SetWidget(0, widgets.QFormLayout__LabelRole, this.Label6)
	this.Label7 = widgets.NewQLabel(this.FormLayoutWidget, core.Qt__Widget)
	this.Label7.SetObjectName("Label7")
	font = gui.NewQFont()
	font.SetWeight(50)
	this.Label7.SetFont(font)
	this..SetWidget(1, widgets.QFormLayout__LabelRole, this.Label7)
	this.XbelPath = widgets.NewQLabel(this.FormLayoutWidget, core.Qt__Widget)
	this.XbelPath.SetObjectName("XbelPath")
	font = gui.NewQFont()
	font.SetWeight(50)
	this.XbelPath.SetFont(font)
	this..SetWidget(1, widgets.QFormLayout__FieldRole, this.XbelPath)
	this. = widgets.NewQWidget(this.GroupBox3, core.Qt__Widget)
	this..SetObjectName("")
	this..SetGeometry(core.NewQRect4(10, 60, 421, 31))
	this.GridLayout = widgets.NewQGridLayout(this.)
	this.GridLayout.SetObjectName("gridLayout")
	this.GridLayout.SetContentsMargins(0, 0, 0, 0)
	this.GridLayout.SetSpacing(0)
	this.GridLayout.SetHorizontalSpacing(40)
	this.XbelLocaltion = widgets.NewQPushButton(this.)
	this.XbelLocaltion.SetObjectName("XbelLocaltion")
	font = gui.NewQFont()
	font.SetWeight(50)
	this.XbelLocaltion.SetFont(font)
	this.GridLayout.AddWidget3(this.XbelLocaltion, 0, 0, 1, 1, 0)
	this.ServerControl = widgets.NewQPushButton(this.)
	this.ServerControl.SetObjectName("ServerControl")
	font = gui.NewQFont()
	font.SetWeight(75)
	this.ServerControl.SetFont(font)
	icon = gui.NewQIcon()
	icon.AddPixmap(gui.NewQPixmap5("../Source/GitHub/LoFloccus/icon.ico", "", core.Qt__AutoColor), gui.QIcon__Normal, gui.QIcon__Off)
	this.ServerControl.SetIcon(icon)
	this.ServerControl.SetCheckable(true)
	this.ServerControl.SetChecked(false)
	this.GridLayout.AddWidget3(this.ServerControl, 0, 1, 1, 1, 0)
	this.HideTray = widgets.NewQPushButton(this.)
	this.HideTray.SetObjectName("HideTray")
	font = gui.NewQFont()
	font.SetWeight(50)
	this.HideTray.SetFont(font)
	this.GridLayout.AddWidget3(this.HideTray, 0, 2, 1, 1, 0)
	this.Label5 = widgets.NewQLabel(this.Centralwidget, core.Qt__Widget)
	this.Label5.SetObjectName("Label5")
	this.Label5.SetGeometry(core.NewQRect4(10, 60, 441, 20))
	font = gui.NewQFont()
	font.SetPointSize(14)
	font.SetWeight(75)
	this.Label5.SetFont(font)
	this.Label5.SetAlignment(core.Qt__AlignCenter)
	this.Label8 = widgets.NewQLabel(this.Centralwidget, core.Qt__Widget)
	this.Label8.SetObjectName("Label8")
	this.Label8.SetGeometry(core.NewQRect4(10, 80, 441, 21))
	font = gui.NewQFont()
	font.SetPointSize(10)
	font.SetWeight(75)
	this.Label8.SetFont(font)
	this.Label8.SetAlignment(core.Qt__AlignCenter)
	this.Label9 = widgets.NewQLabel(this.Centralwidget, core.Qt__Widget)
	this.Label9.SetObjectName("Label9")
	this.Label9.SetGeometry(core.NewQRect4(10, 10, 441, 51))
	this.Label9.SetPixmap(gui.NewQPixmap5("../Source/GitHub/LoFloccus/logo.png", "", core.Qt__AutoColor))
	this.Label9.SetAlignment(core.Qt__AlignCenter)
	MainWindow.SetCentralWidget(this.Centralwidget)
	this.Statusbar = widgets.NewQStatusBar(MainWindow)
	this.Statusbar.SetObjectName("Statusbar")
	MainWindow.SetStatusBar(this.Statusbar)


    this.RetranslateUi(MainWindow)

}

func (this *UILofloccusMainWindow) RetranslateUi(MainWindow *widgets.QMainWindow) {
    _translate := core.QCoreApplication_Translate
	MainWindow.SetWindowTitle(_translate("MainWindow", "LoFloccus - v1.1.0", "", -1))
	MainWindow.SetStatusTip(_translate("MainWindow", "", "", -1))
	this.GroupBox.SetTitle(_translate("MainWindow", "App Settings", "", -1))
	this.StartMinimized.SetText(_translate("MainWindow", "Start minimized to tray/top menu bar", "", -1))
	this.StartOpen.SetText(_translate("MainWindow", "Start server when open", "", -1))
	this.GroupBox2.SetTitle(_translate("MainWindow", "Connect your Floccus (Browser Extension)", "", -1))
	this.Label.SetText(_translate("MainWindow", "1. Open Floccus and choose \"XBEL in WebDav Account\"\n2. Click \"Add Account\" and fill in the following details:", "", -1))
	this.SrvAddr.SetText(_translate("MainWindow", "srv_addr", "", -1))
	this.Label10.SetText(_translate("MainWindow", "Server:", "", -1))
	this.Label11.SetText(_translate("MainWindow", "Username:", "", -1))
	this.SrvUser.SetText(_translate("MainWindow", "srv_user", "", -1))
	this.Label12.SetText(_translate("MainWindow", "Password:", "", -1))
	this.SrvPasswd.SetText(_translate("MainWindow", "srv_passwd", "", -1))
	this.GroupBox3.SetTitle(_translate("MainWindow", "Status", "", -1))
	this.SrvStatus.SetText(_translate("MainWindow", "srv_status", "", -1))
	this.Label6.SetText(_translate("MainWindow", "Server Status:", "", -1))
	this.Label7.SetText(_translate("MainWindow", "XBEL Location:", "", -1))
	this.XbelPath.SetText(_translate("MainWindow", "xbel_path", "", -1))
	this.XbelLocaltion.SetText(_translate("MainWindow", "Change Location", "", -1))
	this.ServerControl.SetText(_translate("MainWindow", "Start Server", "", -1))
	this.HideTray.SetText(_translate("MainWindow", "Hide to Tray", "", -1))
	this.Label5.SetText(_translate("MainWindow", "LoFloccus", "", -1))
	this.Label8.SetText(_translate("MainWindow", "Sync Floccus to a Local Folder!", "", -1))
	this.Label9.SetText(_translate("MainWindow", "", "", -1))
}

```
